#!/bin/sh

echo "Executing remove hook for CalyxVPN"
rm "/usr/share/polkit-1/actions/se.leap.bitmask.calyx-vpn.policy"
unlink "/usr/share/applications/calyx-vpn.desktop" || echo "did not remove workaround for global desktop entry"
echo "done"
